In [1]:
def celsius_fahrenheit():
    # F = (C * 9/5) + 32
    fahrenheit = (22 * (9/5)) + 32
    print(fahrenheit)
    return fahrenheit

In [2]:
celsius_fahrenheit()

71.6

71.6

In [3]:
def celsius_fahrenheit(C):
    # F = (C * 9/5) + 32
    fahrenheit = (C * (9/5)) + 32
    return fahrenheit

In [4]:
celsius_fahrenheit(100)

212.0

In [5]:
celsius_fahrenheit(C=100)

212.0

In [6]:
def fahrenheit_celsius(F):
    # C = (F - 32) * (5/9)
    celsius = (F - 32) * (5/9)
    return celsius

In [7]:
fahrenheit_celsius(212)

100.0

In [9]:
fahrenheit_celsius(71.6)

21.999999999999996

In [10]:
# F=10 is the default if we were to not give it an input
def fahrenheit_celsius(F=10):
    # C = (F - 32) * (5/9)
    celsius = (F - 32) * (5/9)
    return celsius

In [11]:
fahrenheit_celsius()

-12.222222222222223

In [12]:
fahrenheit_celsius(10)

-12.222222222222223

In [13]:
fahr = fahrenheit_celsius(F = 35)

In [14]:
fahr

1.6666666666666667

In [15]:
import pandas as pd

In [16]:
dem_health_data = pd.read_csv("Dem_Health_Full.txt", sep="\t")

In [19]:
dem_health_data.head()

,County,State,Population_Density,Poverty,Infant_Mortality,Suicide,Total_Births,Total_Deaths
0,Autauga,AL,82,10.4,5.9,16.6,3048.0,1867.0
1,Baldwin,AL,102,10.2,7.1,14.3,5471.0,4388.0
2,Barbour,AL,32,22.1,7.1,10.3,1835.0,1538.0
3,Bibb,AL,35,16.8,9.8,14.8,2801.0,2012.0
4,Blount,AL,86,11.9,9.0,14.4,3318.0,2453.0

In [20]:
def get_urban(df):
    urban = df.loc[df['Population_Density'] >= 1000, :]
    return urban

In [21]:
urban_counties = get_urban(dem_health_data)

In [23]:
urban_counties.head()

,County,State,Population_Density,Poverty,Infant_Mortality,Suicide,Total_Births,Total_Deaths
184,Alameda,CA,1964,10.7,4.8,7.6,65423.0,29143.0
190,Contra Costa,CA,1414,7.5,4.0,9.4,39653.0,20836.0
202,Los Angeles,CA,2447,17.7,5.4,7.9,457033.0,181018.0
213,Orange,CA,3785,10.6,4.7,7.6,135702.0,51060.0
217,Sacramento,CA,1412,13.7,5.6,10.9,58592.0,28774.0

In [24]:
def get_urban(df, threshold):
    urban = df.loc[df['Population_Density'] >= threshold, :]
    return urban

In [25]:
urban_counties = get_urban(dem_health_data, 500)

In [26]:
urban_counties.head()

,County,State,Population_Density,Poverty,Infant_Mortality,Suicide,Total_Births,Total_Deaths
36,Jefferson,AL,591,14.4,11.3,11.3,27118.0,21937.0
184,Alameda,CA,1964,10.7,4.8,7.6,65423.0,29143.0
190,Contra Costa,CA,1414,7.5,4.0,9.4,39653.0,20836.0
202,Los Angeles,CA,2447,17.7,5.4,7.9,457033.0,181018.0
213,Orange,CA,3785,10.6,4.7,7.6,135702.0,51060.0

In [27]:
def split_county_by_pop(df, threshold):
    urban = df.loc[df['Population_Density'] >= threshold, :]
    rural = df.loc[df['Population_Density'] < threshold, :]
    return [urban, rural]

In [28]:
urban_rural_counties = \
split_county_by_pop(dem_health_data, 500)

In [35]:
urban_rural_counties[0]

,County,State,Population_Density,Poverty,Infant_Mortality,Suicide,Total_Births,Total_Deaths
36,Jefferson,AL,591,14.4,11.3,11.3,27118.0,21937.0
184,Alameda,CA,1964,10.7,4.8,7.6,65423.0,29143.0
190,Contra Costa,CA,1414,7.5,4.0,9.4,39653.0,20836.0
202,Los Angeles,CA,2447,17.7,5.4,7.9,457033.0,181018.0
213,Orange,CA,3785,10.6,4.7,7.6,135702.0,51060.0
217,Sacramento,CA,1412,13.7,5.6,10.9,58592.0,28774.0
220,San Diego,CA,698,11.6,4.9,10.5,133137.0,59354.0
221,San Francisco,CA,15837,12.0,3.9,11.0,25255.0,18969.0
224,San Mateo,CA,1558,6.8,4.1,7.1,30483.0,14256.0
226,Santa Clara,CA,1316,8.8,4.0,7.6,81257.0,26130.0
227,Santa Cruz,CA,561,11.3,4.0,13.0,10669.0,5098.0
244,Arapahoe,CO,659,7.9,5.0,16.5,23114.0,8722.0
258,Denver,CO,3638,15.1,6.7,14.2,34354.0,13530.0
272,Jefferson,CO,682,6.8,5.5,16.1,19626.0,10089.0
306,Fairfield,CT,1443,7.3,5.3,6.3,36336.0,21011.0
307,Hartford,CT,1193,9.2,6.3,7.6,31212.0,23682.0
310,New Haven,CT,1398,9.4,6.8,7.6,30738.0,23078.0
315,New Castle,DE,1227,8.2,9.4,11.1,21109.0,12346.0
317,Washington,DC,8966,17.5,10.9,6.0,22742.0,17375.0
322,Brevard,FL,522,10.1,6.5,17.5,14613.0,16256.0
323,Broward,FL,1475,12.5,6.5,13.3,67007.0,48248.0
332,Duval,FL,1068,12.8,10.3,14.5,36661.0,20511.0
345,Hillsborough,FL,1077,13.0,8.7,12.6,45253.0,26268.0
352,Lee,FL,678,10.2,6.5,14.3,16382.0,16162.0
360,Miami-Dade,FL,1221,18.9,5.9,9.1,97091.0,55624.0
365,Orange,FL,1127,13.2,7.5,9.9,43304.0,19432.0
367,Palm Beach,FL,643,10.9,7.4,12.5,42293.0,40726.0
368,Pasco,FL,576,11.9,6.6,18.7,11773.0,16150.0
369,Pinellas,FL,3315,12.1,7.6,16.3,27592.0,37641.0
375,Sarasota,FL,641,8.4,5.1,17.1,8618.0,14238.0
...,...,...,...,...,...,...,...,...
2927,Galax City,VA,811,17.9,5.3,19.5,1023.0,1212.0
2928,Hampton City,VA,2811,13.1,11.6,8.5,5611.0,3410.0
2929,Harrisonburg City,VA,2303,17.9,5.9,10.4,2382.0,1298.0
2930,Hopewell City,VA,2216,16.4,10.5,14.4,3525.0,2654.0
2931,Lexington City,VA,2721,16.1,NaN,-1111.1,558.0,767.0
2932,Lynchburg City,VA,1356,17.5,9.2,11.0,4221.0,4057.0
2933,Manassas City,VA,3783,7.5,4.5,-1111.1,3593.0,959.0
2934,Manassas Park City,VA,4667,6.5,6.3,-1111.1,1915.0,347.0
2935,Martinsville City,VA,1362,17.9,2.4,19.9,1907.0,2598.0
2936,Newport News City,VA,2634,14.0,11.7,10.1,9587.0,4220.0
2937,Norfolk City,VA,4317,19.8,11.0,12.6,12143.0,6226.0
2939,Petersburg City,VA,1425,18.5,12.6,9.1,2706.0,2471.0
2940,Poquoson City,VA,761,4.8,6.5,12.8,1267.0,986.0
2941,Portsmouth City,VA,3021,16.5,14.2,13.4,4726.0,3254.0
2942,Radford City,VA,1484,18.5,6.8,19.1,1317.0,1023.0
2943,Richmond City,VA,3226,20.2,14.8,11.5,9287.0,6989.0
2944,Roanoke City,VA,2160,16.9,10.5,16.1,6456.0,6277.0
2945,Salem City,VA,1690,8.4,7.6,11.2,2528.0,3045.0
2946,Staunton City,VA,1184,13.1,6.6,14.5,2527.0,2964.0
2948,Virginia Beach City,VA,1766,8.0,7.1,9.8,18786.0,7655.0
2949,Waynesboro City,VA,1385,13.1,8.1,19.7,2731.0,2330.0
2950,Williamsburg City,VA,1376,17.5,11.2,16.4,1192.0,1288.0
2951,Winchester City,VA,2692,12.0,8.0,15.8,3336.0,2628.0
2957,Clark,WA,643,10.5,5.4,13.8,15927.0,7314.0
2968,King,WA,844,9.4,4.9,10.6,66179.0,34777.0
2969,Kitsap,WA,608,9.2,6.4,11.5,8916.0,5391.0
3075,Kenosha,WI,588,8.8,5.6,13.6,6381.0,3763.0
3086,Milwaukee,WI,3815,16.2,10.4,11.4,43885.0,26557.0
3097,Racine,WI,588,9.3,10.9,11.6,7676.0,4595.0
3113,Waukesha,WI,682,4.1,3.0,8.0,13001.0,8256.0

In [36]:
urban_rural_counties[1].min()

County                Abbeville
State                        AK
Population_Density        -2222
Poverty                     2.2
Infant_Mortality              0
Suicide                 -2222.2
Total_Births            -2222.2
Total_Deaths            -2222.2
dtype: object

In [37]:
len(urban_rural_counties[0])

235

In [39]:
len(urban_rural_counties[1])

2906